// <auto-generated />
namespace ChatDataManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Firstandlastname2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Firstandlastname2));
        
        string IMigrationMetadata.Id
        {
            get { return "202002031416435_First and lastname2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
